import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Review app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
        const isFavoritesPage = typeof window !== 'undefined' && window.location.pathname === '/favorites';
        return (
          <html lang="en">
            <body className={`antialiased`}>
              {!isFavoritesPage && (
                <nav className="bg-transparent shadow mb-6">
                  <div className="container mx-auto px-4 py-4 flex justify-between items-center">
                    <a href="/" className="text-xl font-bold text-white">rA</a>
                    <a href="/favorites" className="text-lg text-white">Favorites</a>
                  </div>
                </nav>
              )}
              {children}
            </body>
          </html>
        );
}
